version: '3.8'

services:
  nginx:
    image: my-nginx:1.0
    container_name: nginx
    restart: always
    network_mode: host
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - /dockerdemo1/ops-learn/nginx-master/tomcat.conf:/etc/nginx/conf.d/tomcat.conf:ro
     - /dockerdemo1/ops-learn/nginx-master/nginx.conf:/etc/nginx/nginx.conf:ro
     - /dockerdemo1/ops-learn/nginx-master/default.conf:/etc/nginx/conf.d/default.conf:ro
